# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 1. Build .NET Shared Library
    - name: Build .NET Contracts
      run: dotnet build ./Common.csproj

    # 2. Install protoc compiler
    - name: Setup protoc
      uses: arduino/setup-protoc@v3.0.0      

    # 3. Setup go env
    - name: Setup Go environment
      uses: actions/setup-go@v5.6.0

    # 4 Install cli toolkit for proto
    - name: Install protoc-gen-go and protoc-gen-go-grpc
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    # 5. Generate Go Code from Protobuf
    - name: Generate Go Protobuf
      run: |
        mkdir -p ./out/pb
        protoc --go_out=./out/pb --go-grpc_out=./out/pb \
        --proto_path=./Protos ./Protos/*.proto
